# Generated by Django 3.2.6 on 2021-08-09 14:18

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('file_name', models.CharField(default='untitled', max_length=300)),
                ('file', models.FileField(upload_to='submitted_queries')),
                ('upload_type', models.CharField(choices=[('hmm', 'hmm'), ('msa', 'msa')], default='hmm', max_length=5)),
                ('processing', models.CharField(choices=[('hmm', 'hmm'), ('observed', 'observed'), ('weighted', 'weighted'), ('hmm_all', 'hmm_all')], default='hmm', max_length=50)),
                ('frag_handling', models.CharField(choices=[('frag', 'frag'), ('full', 'full')], default='full', max_length=50)),
                ('letter_height', models.CharField(choices=[('info_content_all', 'info_content_all'), ('info_content_above', 'info_content_above'), ('score', 'score')], default='info_content_all', max_length=50)),
                ('alphabet', models.CharField(default='unknown', max_length=10)),
                ('hmm_length', models.IntegerField(default=0)),
                ('hmm_created', models.CharField(default='', max_length=50)),
                ('nseq', models.IntegerField(default=0)),
            ],
        ),
    ]
