version: "3.9"

services:

  web:
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:8000 # tail -f /dev/null
    volumes:
      # - ./app/:/app/
      # - ./app/perl_functions:/app/perl_functions
      # - ./app/logo:/app/logo
      - ./app/uploads:/app/uploads
    # restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
      
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=skylign_django

volumes:
  postgres_data: