version: "3.9"

services:

  web:
    build: ./app
    command: gunicorn skylign_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      # - ./app/:/app/
      # - ./app/perl_functions:/app/perl_functions
      # - ./app/logo:/app/logo
      - ./app/uploads:/app/uploads
      - static_volume:/app/staticfiles
    # restart: always
    expose:
      - 8000
    depends_on:
      - db
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=skylign_django

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: