# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "14"

# Install scripts. (runs after repo cloning)
install:
  # node 0.10 & 0.12 have race condition issues when running custom install scripts
  # this can cause phantomjs-prebuilt install script to fail with the error:
  # <Cannot find module 'boom'>
  # Seems related to: https://github.com/npm/npm/issues/8152
  # using <appveyor_retry> solves this.
  
  # change now that we're not using phantomjs?
  - appveyor-retry call npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # Run test
  - cd packages/less && npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
