# Generated by Django 3.1.5 on 2021-01-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='_id',
            new_name='job_id',
        ),
    ]
