# Generated by Django 3.1.5 on 2021-01-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0002_auto_20210114_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='query',
        ),
    ]
