# Generated by Django 3.1.5 on 2021-01-18 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0004_auto_20210115_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
