# Generated by Django 3.1.5 on 2021-01-18 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0006_job_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 12, 11, 11, 153931, tzinfo=utc)),
        ),
    ]
