# Generated by Django 3.1.5 on 2021-01-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0009_job_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='query',
            field=models.FileField(upload_to='submitted_queries'),
        ),
    ]
