# Generated by Django 3.1.5 on 2021-01-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0010_auto_20210118_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='height',
        ),
        migrations.AddField(
            model_name='job',
            name='frag',
            field=models.CharField(default='error', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='letter_height',
            field=models.CharField(default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='processing',
            field=models.CharField(default='error', max_length=50),
        ),
    ]
