# Generated by Django 3.1.5 on 2021-01-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0011_auto_20210119_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='frag',
        ),
        migrations.AddField(
            model_name='job',
            name='alignment_only',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='job',
            name='frag_handling',
            field=models.CharField(default='full', max_length=50),
        ),
    ]
