# Generated by Django 3.1.5 on 2021-01-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0012_auto_20210127_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dna_rna_ok',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='letter_height',
            field=models.CharField(default='info_content_all', max_length=50),
        ),
    ]
